### ISSUE TITLE
Build is broken after wreport updates

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/bufr2netcdf#17]
Bufr2netcdf does not build with current wreport version (3.39)
```
../src/plan.cc: In constructor ‘b2nc::Plan::Plan(const b2nc::Options&)’:
../src/plan.cc:509:24: error: no matching function for call to ‘wreport::_Varinfo::set_bufr(wreport::Varcode, const char [27], const char [11], int, int, int, int)’
  509 |     qbits_info.set_bufr(WR_VAR(0, 33, 0), "Q-BITS FOR FOLLOWING VALUE", "CODE TABLE", 0, 10, 0, 32);
      |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/namer.h:25,
                 from ../src/valarray.h:25,
                 from ../src/plan.h:26,
                 from ../src/plan.cc:22:
/usr/include/wreport/varinfo.h:238:10: note: candidate: ‘void wreport::_Varinfo::set_bufr(wreport::Varcode, const char*, const char*, int, int32_t, unsigned int)’
  238 |     void set_bufr(Varcode code, const char* desc, const char* unit,
      |          ^~~~~~~~
/usr/include/wreport/varinfo.h:238:10: note:   candidate expects 6 arguments, 7 provided
```
and installed executables fail with
```
undefined symbol: _ZN7wreport8_Varinfo8set_bufrEtPKcS2_ijii
```
up to wreport 3.38 it worked. Maybe it should have been wreport 4.0?

**Comment by spanezz** [comment]
It was indeed an accidental API/ABI break in wreport. I opened https://github.com/ARPA-SIMC/wreport/issues/61 to figure what to do

**Comment by spanezz** [comment]
I pushed a fix for wreport, deprecating the function that bufr2netcdf uses, but not breaking it.

I also pushed a branch `issue17` of `bufr2netcdf` that uses a new stable API in the new wreport, that I created for what it needs.

Can you confirm that things work again?

**Comment by dcesari** [comment]
I confirm that bufr2netcdf main branch build and tests now work.
